services:
  streamlit-app:
    build: .
    container_name: streamlit-app
    expose:
      - '8501'
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - .:/app  # Mount project directory to container
      - streamlit-cred:/app/auth  # Mount volume for cred.yml file
    networks:
      - app-network

  mongo:
    image: mongo:4.4
    container_name: mongo
    expose:
      - '27017'
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network
  
  storage-nextcloud:
    container_name: storage-nextcloud
    image: nextcloud:fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - app-network

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - app-network

  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nextcloud_data:/var/www/html
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:  # Named volume for MongoDB data
  streamlit-cred:  # Named volume for cred.yml
  document_data:
  document_log:
  nextcloud_data:
  mysql_data:

  