services:
  streamlit-app:
    image: jeromecoffin/avanta:1.0
    container_name: streamlit-app
    expose:
      - '8501'
    environment:
      - MONGO_URI=mongodb://mongo:27017
    depends_on:
      - mongo
    volumes:
      - streamlit-cred:/app/auth  # Mount volume for cred.yml file
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.5'  # Limit to 50% of 1 vCPU
          memory: 400M  # Limit to 400MB of RAM
        reservations:
          cpus: '0.25'  # Reserve 25% of 1 vCPU
          memory: 200M  # Reserve 200MB of RAM


  mongo:
    image: mongo:4.4
    container_name: mongo
    expose:
      - '27017'
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'  # Limit to 25% of 1 vCPU
          memory: 200M  # Limit to 200MB of RAM
        reservations:
          cpus: '0.1'  # Reserve 10% of 1 vCPU
          memory: 100M  # Reserve 100MB of RAM
  
  storage-nextcloud:
    container_name: storage-nextcloud
    image: nextcloud:fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'  # Limit to 25% of 1 vCPU
          memory: 200M  # Limit to 200MB of RAM
        reservations:
          cpus: '0.1'  # Reserve 10% of 1 vCPU
          memory: 100M  # Reserve 100MB of RAM

  onlyoffice-document-server:
    container_name: onlyoffice-document-server
    image: onlyoffice/documentserver:latest
    restart: always
    environment:
      - JWT_SECRET=secret
    expose:
      - '80'
      - '443'
    volumes:
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.25'  # Limit to 25% of 1 vCPU
          memory: 300M  # Limit to 300MB of RAM
        reservations:
          cpus: '0.15'  # Reserve 15% of 1 vCPU
          memory: 150M  # Reserve 150MB of RAM


  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nextcloud_data:/var/www/html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app-network
    deploy:
      resources:
        limits:
          cpus: '0.1'  # Limit to 10% of 1 vCPU
          memory: 100M  # Limit to 100MB of RAM
        reservations:
          cpus: '0.05'  # Reserve 5% of 1 vCPU
          memory: 50M  # Reserve 50MB of RAM
  
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:  # Named volume for MongoDB data
  streamlit-cred:  # Named volume for cred.yml
  document_data:
  document_log:
  nextcloud_data:
  mysql_data:

  