services:
  streamlit-app:
    image: jeromecoffin/avanta:1.0
    container_name: streamlit-app
    expose:
      - '8501'
    environment:
      - MONGO_URI=${MONGO_URI}
      - NC_USER=${NC_USER}
      - NC_PASS=${NC_PASS}
      - NC_URL=${NC_URL}
    depends_on:
      - mongo
    volumes:
      - streamlit-cred:/app/auth  # Mount volume for cred.yml file
    networks:
      - app-network
    env_file:
      - .env

  mongo:
    image: mongo:4.4
    container_name: mongo
    expose:
      - '27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    volumes:
      - mongo-data:/data/db  
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - app-network
    env_file:
      - .env
  
  storage-nextcloud:
    container_name: storage-nextcloud
    image: jeromecoffin/nextcloud:fpm
    restart: always
    expose:
      - '80'
      - '9000'
    volumes:
      - nextcloud_data:/var/www/html
    networks:
      - app-network

  onlyoffice-document-server: 
    container_name: onlyoffice-document-server
    image: jeromecoffin/onlyoffice:8.1.1
    restart: always
    environment:
      - JWT_SECRET=${JWT_SECRET}
    expose:
      - '80'
      - '443'
    volumes: 
      - document_data:/var/www/onlyoffice/Data
      - document_log:/var/log/onlyoffice
    networks:
      - app-network
    env_file:
      - .env

  nginx:
    container_name: nginx-server
    image: nginx
    restart: always
    ports:
      - 80:80
      - 81:81
      - 443:443
      - 8443:8443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - nextcloud_data:/var/www/html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app-network
  
  certbot:
    image: certbot/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    networks:
      - app-network


networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:  
  streamlit-cred:  
  document_data:
  document_log:
  nextcloud_data:
  mysql_data:

  